{"name": "Ошибка повторного создания одного и того же курьера", "status": "passed", "description": "Проверка, что нельзя создать одного и того же курьера дважды", "start": 1701558793321, "stop": 1701558793831, "uuid": "869210f5-1d5a-4328-b4ac-5538778a3715", "historyId": "6460a6fdcf9c3d60cfc93300ff072708", "testCaseId": "6460a6fdcf9c3d60cfc93300ff072708", "fullName": "test.test_create_courier.TestCreateCourier#test_create_courier_two_same_error_login", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "DESKTOP-QRA353I"}, {"name": "thread", "value": "13296-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_create_courier"}]}